---
config:
  apis:
    jenkins:
      wendy_scripts: "https://api/json?pretty=true"
      jenkins_timer: 120
    tracker:
      envs:
        pp1: "https://pp1.yaml"
        pp2: "https://pp2.yaml"
        pp3: "https://pp3.yaml"
        sc1: "https://prd.yaml"
      tracker_timer: 60
    certs:
      certs_path: "/certificates/SSL/"
      certs_exten: ".crt"
